"use client";

/**
 * Signup form — shadcn signup-04 styling, our /api/auth/signup wiring.
 *
 * Generated by `npx shadcn@latest add signup-04` and adapted:
 *   - extra fields the gateway requires (full_name, company_name, …)
 *   - real validation: passwords must match and be ≥ 8 chars
 *   - on success shows a "check your email" state since signup is
 *     async (gateway emails a verification link)
 *   - OAuth panel removed
 */

import Link from "next/link";
import { useState } from "react";

import { useRef } from "react";

import { api, ApiError, GATEWAY } from "@/lib/api";
import { Recaptcha, type RecaptchaHandle } from "@/components/Recaptcha";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import {
  Field,
  FieldDescription,
  FieldGroup,
  FieldLabel,
} from "@/components/ui/field";
import { Input } from "@/components/ui/input";

type SignupFields = {
  full_name: string;
  email: string;
  password: string;
  confirm_password: string;
  company_name: string;
};

export function SignupForm({
  className,
  ...props
}: React.ComponentProps<"div">) {
  const [form, setForm] = useState<SignupFields>({
    full_name: "",
    email: "",
    password: "",
    confirm_password: "",
    company_name: "",
  });
  const [busy, setBusy] = useState(false);
  const [done, setDone] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const recaptchaRef = useRef<RecaptchaHandle>(null);

  function set<K extends keyof SignupFields>(k: K, v: SignupFields[K]) {
    setForm((s) => ({ ...s, [k]: v }));
  }

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    if (form.password !== form.confirm_password) {
      setError("Passwords don't match");
      return;
    }
    if (form.password.length < 8) {
      setError("Password must be at least 8 characters");
      return;
    }
    setBusy(true);
    setError(null);
    try {
      const recaptcha_token = (await recaptchaRef.current?.execute()) ?? undefined;
      // The gateway expects snake_case fields. Confirm_password is a UI-only
      // check; we don't send it.
      await api("/api/auth/signup", {
        method: "POST",
        body: JSON.stringify({
          full_name: form.full_name,
          email: form.email,
          password: form.password,
          company_name: form.company_name,
          recaptcha_token,
        }),
        auth: false,
      });
      setDone(true);
    } catch (err) {
      setError(err instanceof ApiError ? err.message : "Signup failed");
    } finally {
      setBusy(false);
    }
  }

  if (done) {
    return (
      <div className={cn("flex flex-col gap-6", className)} {...props}>
        <Card className="overflow-hidden p-0">
          <CardContent className="p-8 text-center">
            <h1 className="text-2xl font-bold">Check your email</h1>
            <p className="mt-2 text-sm text-muted-foreground">
              We&apos;ve sent a verification link to{" "}
              <span className="font-medium">{form.email}</span>. Open it to
              finish setting up your workspace. The link is valid for 24 hours.
            </p>
            <p className="mt-4 text-xs text-muted-foreground">
              Wrong email or didn&apos;t receive it?{" "}
              <button
                type="button"
                className="underline"
                onClick={() => setDone(false)}
              >
                Try again
              </button>
            </p>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className={cn("flex flex-col gap-6", className)} {...props}>
      <Card className="overflow-hidden p-0">
        <CardContent className="grid p-0 md:grid-cols-2">
          <form onSubmit={submit} className="p-6 md:p-8">
            <FieldGroup>
              <div className="flex flex-col items-center gap-2 text-center">
                <h1 className="text-2xl font-bold">Create your account</h1>
                <p className="text-sm text-balance text-muted-foreground">
                  Start your SalesChimp workspace in about 30 seconds.
                </p>
              </div>
              <Field>
                <FieldLabel htmlFor="full_name">Full name</FieldLabel>
                <Input
                  id="full_name"
                  value={form.full_name}
                  onChange={(e) => set("full_name", e.target.value)}
                  required
                  maxLength={128}
                />
              </Field>
              <Field>
                <FieldLabel htmlFor="company_name">Company name</FieldLabel>
                <Input
                  id="company_name"
                  value={form.company_name}
                  onChange={(e) => set("company_name", e.target.value)}
                  required
                  maxLength={128}
                />
              </Field>
              <Field>
                <FieldLabel htmlFor="email">Work email</FieldLabel>
                <Input
                  id="email"
                  type="email"
                  placeholder="you@example.com"
                  value={form.email}
                  onChange={(e) => set("email", e.target.value)}
                  required
                />
                <FieldDescription>
                  We&apos;ll use this to contact you. We won&apos;t share it.
                </FieldDescription>
              </Field>
              <Field>
                <Field className="grid grid-cols-2 gap-4">
                  <Field>
                    <FieldLabel htmlFor="password">Password</FieldLabel>
                    <Input
                      id="password"
                      type="password"
                      autoComplete="new-password"
                      value={form.password}
                      onChange={(e) => set("password", e.target.value)}
                      required
                    />
                  </Field>
                  <Field>
                    <FieldLabel htmlFor="confirm_password">
                      Confirm Password
                    </FieldLabel>
                    <Input
                      id="confirm_password"
                      type="password"
                      autoComplete="new-password"
                      value={form.confirm_password}
                      onChange={(e) => set("confirm_password", e.target.value)}
                      required
                    />
                  </Field>
                </Field>
                <FieldDescription>
                  Must be at least 8 characters.
                </FieldDescription>
              </Field>
              <Recaptcha ref={recaptchaRef} gateway={GATEWAY} action="signup" />
              {error && (
                <div className="rounded-md bg-destructive/10 px-3 py-2 text-sm text-destructive">
                  {error}
                </div>
              )}
              <Field>
                <Button type="submit" disabled={busy}>
                  {busy ? "Creating…" : "Create account"}
                </Button>
              </Field>
              <FieldDescription className="text-center">
                Already have an account?{" "}
                <Link href="/login" className="underline">
                  Sign in
                </Link>
              </FieldDescription>
            </FieldGroup>
          </form>
          {/* Same decorative gradient as login. */}
          <div
            className="relative hidden md:block bg-gradient-to-br from-primary/20 via-primary/5 to-background dark:from-primary/40 dark:via-primary/10"
            aria-hidden="true"
          />
        </CardContent>
      </Card>
      <FieldDescription className="px-6 text-center">
        By creating an account you agree to our{" "}
        <a href="#" className="underline">
          Terms of Service
        </a>{" "}
        and{" "}
        <a href="#" className="underline">
          Privacy Policy
        </a>
        .
      </FieldDescription>
    </div>
  );
}
